# Generated by Django 4.1.3 on 2022-12-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_member_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
